// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJ0fKSK2ssN24lgRMBEHdk0atYXsiDkQ',
    appId: '1:886967521798:web:b8322103bf4e81caabe987',
    messagingSenderId: '886967521798',
    projectId: 'cinemaster-app',
    authDomain: 'cinemaster-app.firebaseapp.com',
    storageBucket: 'cinemaster-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmH9zxIIorV7hyS28henwOlmUecb2Xyg',
    appId: '1:886967521798:android:a255e1a9ec5c796eabe987',
    messagingSenderId: '886967521798',
    projectId: 'cinemaster-app',
    storageBucket: 'cinemaster-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFeQ5sTw26yNbRluiEZ2FuaKc93eRuD4',
    appId: '1:886967521798:ios:e67507d08df9f799abe987',
    messagingSenderId: '886967521798',
    projectId: 'cinemaster-app',
    storageBucket: 'cinemaster-app.appspot.com',
    iosBundleId: 'com.example.cinemasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFeQ5sTw26yNbRluiEZ2FuaKc93eRuD4',
    appId: '1:886967521798:ios:561e28f9b119ac92abe987',
    messagingSenderId: '886967521798',
    projectId: 'cinemaster-app',
    storageBucket: 'cinemaster-app.appspot.com',
    iosBundleId: 'com.example.cinemasterApp.RunnerTests',
  );
}
